[package]
name = "genlang_rust"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"peeking_take_while" = "0.1.2"
lazy_static = "1.4.0"
rand = "0.8.4"
maplit = "1.0.2"
