[package]
name = "brevis"
version = "0.0.1"

[[bin]]
name = "brevis"

[profile.release]
debug = 1

[workspace]

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
regex = "1"
brevis-lib = { path = "./lib/" }
